on:
  push:
    branches:
      - main
name: 🚀 PROD DEPLOY Bot
jobs:
  deploy_to_prod:
    name: 🎉 PROD Deploy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Deploy files via SFTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        # SFTP credentials
        host: ${{ secrets.FPT_HOST }}
        port: ${{ secrets.FTP_PORT }}
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        # lftp settings
        onlyNewer: true
        settings: 'sftp:auto-confirm=yes'
        # Mirror command options
        localDir: '.'
        remoteDir: '.'
        reverse: true
        ignoreFile: '.env logs/* data/*'
        options: '--exclude-glob=.git*/ --verbose'
